export interface IListaOrdenCompra{
    hasItems : boolean, 
    items : IOrdenCompra[];
    total : number,
    page : number,
    pages : number,
    label : string
 }

export interface IOrdenCompra{
    idCompra: number,
    nroRegistro: string,
    tipoDocumento: string,
    nroDocumento: string,
    fechaEmision: string,
    fechaVencimiento: string,
    proveedorDocumento: string,
    proveedorNombreRazSocial: string,
    moneda: string,
    importe: number,
    saldo:number,
    vendedor: string,
    fechaRegistro: string,
    usuarioRegistro: string,
    correlativoMensual: number,
    monedaId: number,
    serie: string,
    secuencial: number,
}

export interface ICreateOrdenCompra{   
    establecimientoid: number,
    documentoid: number,
    idproveedor: number,
    serieventa: string,
    secuencialventa: number,
    fechaemision: string,
    condicionpagoid: number,
    nombrecliente: string,
    direccioncliente: string,
    monedaid: number,
    tipocambio: number,
    diasvencimiento:number,
    fechavencimiento: string,
    glosa: string,
    estadoid: boolean,
    dsctoglobalimporte: number,
    codtipooperacion: string,
    esdeduccionanticipo: boolean,
    esafectodetraccion:boolean,
    esafectoretencion:boolean,
    motivonotaid: number,
    esrecargoconsumo:boolean,
    cantidadtotal: number,
    importeanticipo: number,
    importedescuento: number,
    importevalorventa: number,
    importeigv: number,
    importeicbper: number,
    importeotrostributos: number,
    importetotalventa: number,
    importepercepcion: number,
    esordencompra: boolean,
    detalles: IDetalleOrdenCompra[], 
    documentoReferenciaDtos: string[],
    ordenCompraCmd:  IOrdenCompraCMD, 
    idsToDelete: number[],
    compraid : number,
    correlativomensual: number
 }

 export interface IDetalleOrdenCompra{
    compraAnticipoReferencia: boolean,
    compradetalleid: number,
    compraid: number,
    productoid: number,
    almacenid: number,
    unidadmedidaid: number,
    codproductofinal: string,
    descripcionproducto: string,
    cantidad: number,
    preciounitario: number,
    precioincluyeigv: boolean,
    baseimponible: number,
    tipoafectacionid: number,
    porcentajedescuento: number,
    observaciones: string,
    importedescuento: number,
    esanticipo: boolean,
    valorventa: number,
    igv: number,
    importeotroscargos: number,
    importeicbper: number,
    precioventa: number,
    nrolote: string,
    fechavencimiento: string,
    nroserie: string,
    ventadetallemigradaid: number,
    despachado: number,
    compraanticipoid: number,
    valordetraccionmn: number,
    valordetraccionme: number,
 }
 export interface IOrdenCompraCMD {
    ordencompraid :number,
    estadoextraccionid :number,
    formapagoid :number,
    areasolicitanteid :number,
    tipoordencompraid :number,
    notalugarentrega : string,
    notaanexos : string,
    notaobservaciones : string, 
 }
 export interface IOrdenCompraPorId{ 
    detalles : IDetalleOrdenCompra[],
    nroDocumentoCliente: string,
    nroRegistro: string,
    ordenCompraCmd: IOrdenCompraCMD,
    documentoReferenciaDtos: null,
    compraid: number,
    correlativomensual: number,
    establecimientoid: number,
    documentoid: number,
    idproveedor: number,
    serieventa: string,
    secuencialventa: number,
    fechaemision: string,
    condicionpagoid: number,
    nombrecliente:string,
    direccioncliente: string,
    monedaid: number,
    tipocambio: number,
    diasvencimiento: number,
    fechavencimiento: string,
    glosa: string,
    estadoid: boolean,
    dsctoglobalrporcentaje: number,
    dsctoglobalimporte: number,
    codtipooperacion: string,
    esdeduccionanticipo: boolean,
    esafectodetraccion: boolean,
    codigodetraccion: string,
    porcentajedetraccion: number,
    esafectoretencion: boolean,
    motivonotaid: number,
    ordenservicio: number,
    ordencompra: number,
    fechaordencompra: string,
    esrecargoconsumo: boolean,
    cantidadtotal: number,
    importeanticipo: number,
    importedescuento: number,
    importevalorventa: number,
    importeigv: number,
    importeicbper: number,
    importeotrostributos: number,
    importetotalventa: number,
    idauditoria: number,
    nrodetraccion: string,
    fechadetraccion: string,
    esafectopercepcion: boolean,
    tipodocpercepcion: number,
    seriepercepcion: string,
    serialpercepcion: number,
    fechapercepcion: string,
    importebasepercepcion: number,
    porcentajepercepcion: number,
    importepercepcion: number,
    esordencompra: boolean,
    ordencompraid :number,
 }