export interface IListarCompra{
    hasItems : boolean,
    items : ICompra[],
    label : string,
    page : number,
    pages : number,
    total : number
}

export interface ICompra{
    idCompra: number,
    nroRegistro: string,
    tipoDocumento: string,
    nroDocumento: string,
    fechaEmision: string,
    fechaVencimiento: string,
    proveedorDocumento: string,
    proveedorNombreRazSocial: string,
    moneda: string,
    importe: number,
    saldo:number,
    vendedor: string,
    fechaRegistro: string,
    usuarioRegistro: string,
    correlativoMensual: number,
    monedaId: 1,
    serie: string,
    secuencial: number,
}


export interface ICrearCompra{ 
    compraid : number,
    correlativomensual : number,
    establecimientoid: number,
    documentoid: number,
    idproveedor: number,
    serieventa: string,
    secuencialventa : number,
    fechaemision: string,
    condicionpagoid: number,
    nombrecliente: string,
    direccioncliente: string,
    monedaid: number,
    tipocambio: number,
    diasvencimiento: number,
    fechavencimiento: string,
    glosa : string,
    estadoid: boolean,
    dsctoglobalrporcentaje: number,
    dsctoglobalimporte: number,
    codtipooperacion: string,
    esdeduccionanticipo: boolean,
    esafectodetraccion: boolean,
    codigodetraccion: string,
    porcentajedetraccion: number, 
    esafectoretencion: boolean,
    motivonotaid: number,
    esrecargoconsumo:boolean,
    cantidadtotal : number,
    importeanticipo: number,
    importedescuento: number,
    importevalorventa: number,
    importeigv: number,
    importeicbper:number,
    importeotrostributos:number,
    importetotalventa: number,
    idauditoria : number,
    nrodetraccion: string,
    fechadetraccion : string,
    esafectopercepcion:boolean,
    tipodocpercepcion:number,
    fechapercepcion: string // por confirmar
    seriepercepcion: string,
    serialpercepcion : number, 
    importebasepercepcion: number,
    porcentajepercepcion: number,
    importepercepcion: number,
    detalles : IDetalleCompra[],
    documentoReferenciaDtos: IDocumentoReferenciaDTO[],
    idsToDelete : number[],
    conceptocontableid  : number
}


export interface IDetalleCompra{
    compradetalleid : number,
    compraid : number,
    productoid: number,
    almacenid: number,
    unidadmedidaid: number,
    codproductofinal: string,
    descripcionproducto: string,
    cantidad: number,
    preciounitario: number,
    precioincluyeigv: boolean,
    baseimponible: number,
    tipoafectacionid: number,
    porcentajedescuento: number,
    observaciones: string,
    importedescuento: number,
    esanticipo: boolean,
    valorventa: number,
    igv: number,
    importeotroscargos: number,
    precioventa: number,
    nrolote: string,
    fechavencimiento: string,
    nroserie: string,
    valordetraccionmn: number,
    valordetraccionme:number,
    importeicbper:number, 
    compraAnticipoReferencia:number,
    ventadetallemigradaid:number,
    despachado:number,
    compraanticipoid:number, 
    nrocuenta : string 
}

export interface IDocumentoReferenciaDTO{
    compradocumentosreferenciaid: number,
    compraid : number
    idproveedor : number,
    documentoid : number,
    seriereferencia : string,
    secuencialreferencia: string,
    esgrm : boolean,
    fechadocref :string,
}


export interface ICompraPorId{ 
    establecimientoid: number,
    documentoid: number,
    idproveedor: number,
    serieventa: string,
    secuencialventa : number,
    fechaemision: string,
    condicionpagoid: number,
    nombrecliente: string,
    direccioncliente: string,
    monedaid: number,
    tipocambio: number,
    diasvencimiento: number,
    fechavencimiento: string,
    estadoid: boolean,
    dsctoglobalrporcentaje: number,
    dsctoglobalimporte: number,
    codtipooperacion: string,
    esdeduccionanticipo: boolean,
    esafectodetraccion: boolean,
    codigodetraccion: string,
    porcentajedetraccion: number
    esafectoretencion: boolean,
    motivonotaid: number,
    esrecargoconsumo:boolean,
    cantidadtotal : number,
    importeanticipo: number,
    importedescuento: number,
    importevalorventa: number,
    importeigv: number,
    importeicbper:number,
    importeotrostributos:number,
    importetotalventa: number,
    nrodetraccion: string,
    esafectopercepcion:boolean,
    tipodocpercepcion:number,
    seriepercepcion: string,
    serialpercepcion : number, 
    importebasepercepcion: number,
    porcentajepercepcion: number,
    importepercepcion: number,
    detalles : IDetalleCompra[],
    documentoReferenciaDtos: IDocumentoReferenciaDTO[],
    compraid : number,
    vendedorid : number,
    correlativomensual: number,
    idauditoria : number,
    glosa : string,
    nroDocumentoCliente: string,
    nroRegistro: string,
    ordenservicio : number,
    ordencompra: number,
    fechaordencompra : string,
    fechadetraccion: string,
    fechapercepcion: string,
    conceptocontableid  :number
}