export interface IListarGuiasRemision {
    hasItems : boolean,
    items : IGuiasRemision[],
    label : string,
    page : number,
    pages : number,
    total : number
}

export interface IGuiasRemision {
    cliente : string,
    docGuia : string,
    docReferencia : string,
    fechaEmision : string,
    fechaRegistro : string,
    fechaTraslado : string,
    id : number,
    nroRegistro : string,
    ordenCompra : number,
    secuencialDocRef: number,
    secuencialGuia : number,
    serieDocRef : number,
    serieGuia : string,
    siglasDocRef: string,
    transportista: string,
    ubigeoLlegada : number,
    ubigeoLlegadaUbicacion : string,
    usuarioRegistro : string
}


export interface ICrearGuiasRemision {
    correlativomensual : number,
    detalles: IGuiaDetalle[],
    estadoid: boolean,
    establecimientoid: number,
    fechaemision : string,
    fechatraslado : string,
    guiaremisionid: number,
    idauditoria: number,
    idcliente: number,
    idsToDelete : number[],
    importetotal: number,
    llegadadireccion : string,
    llegadaubigeo :  number,
    modalidadid:  number,
    motivoid: number,
    monedaid: number,
    observacion:string,
    ordencompra :  number,
    partidadireccion : string,
    partidaubigeo :  number,
    pedidocot : number,
    pesototal: number,
    redondeo: number,
    secuencialref: number,
    seriedocumentoref :  number,
    secuencialguia: number,
    serieguia : string,
    tipocambio: number,
    tipodocumentoid: number,
    tipodocumentoidref: number,
    totalbultos: number,
    transportistaid: number,
    transportistachoferid: number,
    transportistaunidadid: number,
}

export interface IGuiaDetalle{
    almacenid: number,
    bultos: number,
    cantidad: number,
    codproductofinal: string
    descripcionproductofinal: string,
    guiaremisiondetalleid: number,
    guiaremisionid: number,
    idauditoria?: number,
    pesototal: number,
    pesounitario: number,
    preciounitario: number,
    productoid: number,
    unidadmedidaid:  number,
}

 
export interface IGuiaRemisionPorId {
    breveteChofer :string,
    certificadoUT: string,
    codCliente : string,
    codigoTransportista : string,
    correlativomensual : number,
    detalles : IGuiaDetalle[],
    establecimientoid: number,
    estadoid: boolean,
    fechaemision : string,
    fechatraslado : string,
    guiaremisionid: number,
    idauditoria: number,
    idcliente : number,
    importetotal : number,
    llegadadireccion : string,
    llegadaubigeo: number,
    marcaPlacaUT: string,
    modalidadid : number,
    monedaid : number,
    motivoid : number,
    nombreCliente : string,
    nombreTransportista: string,
    nroRegistro: string,
    observacion: string,
    ordencompra: number,
    partidadireccion : string,
    partidaubigeo : number,
    pedidocot : number,
    pesototal : number,
    redondeo : number,
    rucCliente : number,
    rucTransportista : number,
    secuencialguia : number,
    secuencialref : number,
    seriedocumentoref : number,
    serieguia : string,
    tipocambio: number,
    tipodocumentoid : number,
    tipodocumentoidref: number,
    totalbultos : number,
    transportistachoferid: number,
    transportistaid : number,
    transportistaunidadid: number

}